chrome_path = chrome_path = r'C:\bin\selenium\chromedriver230.exe'

url_for_test = [
    # 'about',
    # 'services',
    # 'layaway-plan',
    # '30-day-satisfaction-guarantee'
    # 'buy-now-pay-later',
    # 'buying-online',
    # 'carat-weight-tolerance',
    # 'contact-us',
    # 'customer-service',
    # 'customer-spotlight',
    # 'diamond-overview',
    # 'diamond-trends',
    # 'education',
    # 'for-the-perfect-match',
    # 'free-shipping',
    # 'full-brilliance-collection',
    # 'gold-overview',
    # 'ladies-wedding-bands',
    # 'mens-wedding-bands',
    # 'military',
    # 'my-trio-rings-in-the-news',
    # 'platinum-jewelry',
    'plus-size-wedding-ring-sets',
    'requesting-an-ma',
    'revelinrose',
    'ring-fit-types',
    'ring-size-guide',
    # 'same-sex-wedding-bands',
    # 'she-said-yes-special',
    # 'stackable-trio',
    # 'student',
    # 'the-4cs',
    # 'todays-diamond-industry',
    # 'trio-rings',
    # 'understanding-diamond-grading',
    # 'us-vs-them',
    # 'warranty-and-repairs',
    # 'ways-to-pay',
    # 'wedding-ring-sets-on-a-budget',
    # 'what-is-a-trio-wedding-ring-set',
    # 'worry-free-shopping',
    # 'bridal-rings',
    # 'engagement-rings',
]
